# -*- coding: utf-8 -*-
"""Tech Sagar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PRhobyNASpVXvK4O8ICTUZn7wTyHGsa
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/TechSagar/sample.csv')

import re

# 1. Merge amt into transaction_amount where it is NaN
df['transaction_amount'] = df['transaction_amount'].fillna(df['amt'])

df

df.drop(columns=['amt'], inplace=True)

import numpy as np

# Clean currency (Remove ₹, Rs, INR, commas, spaces, etc.)
def clean_currency(val):
    if pd.isna(val): return np.nan
    val_str = str(val).strip().lower()
    if val_str in ['(null)', 'null', 'nan', 'none', 'n/a']: return np.nan
    val_str = re.sub(r'[₹|rs|inr|,|\s]', '', val_str)
    return pd.to_numeric(val_str, errors='coerce')

df['transaction_amount'] = df['transaction_amount'].apply(clean_currency)

#1. Clean 'merchant_category'
# Fill missing with 'Others' and convert to Title Case
df['merchant_category'] = df['merchant_category'].fillna('Others').str.title()

df

# Create soft fraud score instead of hard label
signal_cols = [
    'label_ato','label_cnp','label_new_device_struct',
    'label_bad_ip','label_overdraft','label_micro_probe','label_extreme_amount'
]

df['fraud_score'] = df[signal_cols].sum(axis=1)

# Normalize score (0 to 1)
df['fraud_score_norm'] = df['fraud_score'] / len(signal_cols)

# Use threshold but NOT strict
df['is_fraud_soft'] = (df['fraud_score_norm'] > 0.3).astype(int)

# 2. Clean 'payment_method'
# Standardize to UPPERCASE and fill missing with 'UNKNOWN'
df['payment_method'] = df['payment_method'].fillna('UNKNOWN').str.upper()

df['rolling_avg_3'] = df.groupby('user_id')['transaction_amount'].transform(lambda x: x.rolling(3, min_periods=1).mean())

# Spike detection
df['spike_flag'] = (df['transaction_amount'] > 2 * df['rolling_avg_3']).astype(int)

from sklearn.ensemble import IsolationForest

iso = IsolationForest(contamination=0.05, random_state=42)

iso_features = [
    'transaction_amount', 'amount_vs_user_avg',
    'seconds_since_prev', 'txn_count_last_5min',
    'amount_to_balance_ratio'
]

df['iso_score'] = iso.fit_predict(df[iso_features].fillna(0)) # Fillna with 0 for IsolationForest
df['iso_score'] = df['iso_score'].map({1:0, -1:1})  # anomaly = 1

df
y = df['is_fraud_soft']

# 3. Clean 'transaction_status'
# Image suggest filtering: Only keep 'success', 'pending', 'failed'
valid_statuses = ['success', 'pending', 'failed']
df = df[df['transaction_status'].str.lower().isin(valid_statuses)]

df



import pandas as pd
import re
from dateutil import parser
import numpy as np

def parse_timestamp(x):
    """
    Robust parser for transaction_timestamp column
    Special handling for DD-MM-HH:MM:SS.mmm format (assumes 2024)
    Returns timezone-naive pd.Timestamp or pd.NaT
    """
    if pd.isna(x) or str(x).strip() in ['', 'null', 'NULL', 'NA', 'N/A', '-']:
        return pd.NaT

    x = str(x).strip()

    # ─── Special case: DD-MM-HH:MM:SS.mmm ───────────────────────────────
    # Examples: 01-04-11:41:45.267   01-03-17:13:06.776
    if re.match(r'^\d{2}-\d{2}-\d{2}:\d{2}:\d{2}\.\d{3}$', x):
        try:
            dd, rest = x.split('-', 1)
            mm, time_part = rest.split('-', 1)
            full_str = f"2024-{mm.zfill(2)}-{dd.zfill(2)} {time_part}"
            return pd.to_datetime(full_str, format="%Y-%m-%d %H:%M:%S.%f")
        except:
            pass  # fall through to other parsers

    # ─── Quick numeric path (unix timestamp) ─────────────────────────────
    if re.match(r'^\d+$', x):
        try:
            num = float(x)
            if num > 1e12:  # milliseconds
                return pd.to_datetime(num, unit='ms')
            elif num > 1e9:  # seconds
                return pd.to_datetime(num, unit='s')
        except:
            pass

        # Compact YYYYMMDDHHMMSS
        if len(x) == 14:
            try:
                return pd.to_datetime(x, format='%Y%m%d%H%M%S')
            except:
                pass

    # ─── Fuzzy natural language parse ────────────────────────────────────
    try:
        return parser.parse(x, fuzzy=True, dayfirst=True, yearfirst=False)
    except:
        pass

    # ─── Explicit common formats ─────────────────────────────────────────
    formats = [
        '%d-%m-%Y %H:%M:%S',
        '%d/%m/%Y %H:%M',
        '%Y-%m-%d %H:%M:%S',
        '%Y/%m/%d %H:%M',
        '%d-%b-%Y',
        '%d %b %Y',
        '%d-%b-%Y %H:%M',        # extra common in India
        '%d %b %Y %H:%M:%S',
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(x, format=fmt, errors='raise')
        except:
            continue

    # Nothing matched
    return pd.NaT


# ────────────────────────────────────────────────
# Apply parsing
df['transaction_timestamp'] = df['transaction_timestamp'].astype(str).str.strip()
df['ts'] = df['transaction_timestamp'].apply(parse_timestamp)

# ─── Remove timezone from ALL timestamps (prevents sorting error) ───────
df['ts'] = df['ts'].dt.tz_localize(None)

# ─── Quality report ─────────────────────────────────────────────────────
success = df['ts'].notna().sum()
total   = len(df)
fail    = total - success

print(f"Successfully parsed: {success:,} / {total:,} rows")
print(f"Failed to parse    : {fail:,} ({fail/total:.2%})")

if fail > 0:
    print("\nFailed timestamp examples (first 10 unique):")
    failed_samples = df[df['ts'].isna()]['transaction_timestamp'].dropna().unique()[:10]
    print(failed_samples.tolist())

# ─── Sorting (should now work without TypeError) ────────────────────────
df = df.sort_values(['user_id', 'ts']).reset_index(drop=True)

# Quick sanity check
print("\nDate range after sorting:")
print("Earliest:", df['ts'].min())
print("Latest:  ", df['ts'].max())
print("Any remaining NaT?", df['ts'].isna().any())



df

import pandas as pd
import numpy as np

# ────────────────────────────────────────────────
# Much more complete map — covers ~80–95% in most Indian fintech datasets
city_map = {
    # Mumbai + variants
    'mumbai': 'Mumbai', 'bombay': 'Mumbai', 'bom': 'Mumbai', 'mum': 'Mumbai',
    'mumbai ': 'Mumbai', ' mumbai': 'Mumbai', 'mumabi': 'Mumbai', 'mumabai': 'Mumbai',
    'navimumbai': 'Navi Mumbai', 'navi mumbai': 'Navi Mumbai', 'navi-mumbai': 'Navi Mumbai',

    # Bengaluru
    'bangalore': 'Bengaluru', 'bengaluru': 'Bengaluru', 'banglore': 'Bengaluru',
    'blr': 'Bengaluru', 'benagluru': 'Bengaluru', 'bangaluru': 'Bengaluru',
    'bangalor': 'Bengaluru', 'benguluru': 'Bengaluru',

    # Chennai + variants
    'chennai': 'Chennai', 'madras': 'Chennai', 'chennnai': 'Chennai',
    'chenai': 'Chennai', 'chennnai': 'Chennai', 'chennal': 'Chennai',

    # Kolkata
    'kolkata': 'Kolkata', 'calcutta': 'Kolkata', 'calcuta': 'Kolkata',
    'kolkatta': 'Kolkata', 'colkata': 'Kolkata',

    # Delhi / NCR
    'delhi': 'Delhi', 'new delhi': 'Delhi', 'ncr': 'Delhi', 'newdelhi': 'Delhi',
    'new-delhi': 'Delhi', 'gurgaon': 'Gurgaon', 'gurugram': 'Gurugram',
    'noida': 'Noida', 'greater noida': 'Greater Noida',

    # Hyderabad
    'hyderabad': 'Hyderabad', 'hyd': 'Hyderabad', 'hyderbad': 'Hyderabad',

    # Pune
    'pune': 'Pune', 'punr': 'Pune', 'poona': 'Pune',

    # Ahmedabad
    'ahmedabad': 'Ahmedabad', 'ahmdabad': 'Ahmedabad', 'amdavad': 'Ahmedabad',

    # Jaipur
    'jaipur': 'Jaipur', 'jaypur': 'Jaipur',

    # Lucknow
    'lucknow': 'Lucknow', 'lukhnow': 'Lucknow',

    # Surat
    'surat': 'Surat',

    # Other frequent ones
    'indore': 'Indore', 'bhopal': 'Bhopal', 'patna': 'Patna',
    'coimbatore': 'Coimbatore', 'kochi': 'Kochi', 'ernakulam': 'Kochi',
    'thiruvananthapuram': 'Thiruvananthapuram', 'trivandrum': 'Thiruvananthapuram',
    'visakhapatnam': 'Visakhapatnam', 'vizag': 'Visakhapatnam',
}

# ────────────────────────────────────────────────
def normalize_city_advanced(col_name):
    """
    Returns normalized city names + detailed success statistics
    """
    # Step 1: clean input
    s = df[col_name].astype(str).str.lower().str.strip()

    # Step 2: treat obvious missing/invalid as NaN
    missing_markers = ['', 'nan', 'na', 'n/a', 'null', '-', 'unknown', 'none', 'nil', 'missing']
    s = s.replace(missing_markers, np.nan)

    # Step 3: map known aliases
    mapped = s.map(city_map)

    # Step 4: fallback → title case only for values that look like real city names
    fallback = s.str.title()
    # Very short or numeric-looking → keep as NaN
    fallback = np.where(
        (s.str.len() <= 2) | s.str.match(r'^\d'), np.nan, fallback
    )

    result = mapped.combine_first(pd.Series(fallback, index=s.index))

    # ── Statistics ────────────────────────────────────────
    total_rows = len(df)
    original_non_null = df[col_name].notna().sum()
    after_non_null   = result.notna().sum()
    mapped_to_known  = result.isin(city_map.values()).sum()

    print(f"\n=== LOCATION NORMALIZATION REPORT: {col_name} ===")
    print(f"Total rows                     : {total_rows:,}")
    print(f"Original non-null values       : {original_non_null:,} ({original_non_null/total_rows*100:.2f}%)")
    print(f"After normalization non-null   : {after_non_null:,} ({after_non_null/total_rows*100:.2f}%)")
    print(f"→ Mapped to known canonical    : {mapped_to_known:,} ({mapped_to_known/total_rows*100:.2f}%)")
    print(f"→ Title-cased (still unknown)  : {after_non_null - mapped_to_known:,} ({(after_non_null - mapped_to_known)/total_rows*100:.2f}%)")

    # Show top unmapped cities — this is the most important part!
    unmapped = result[result.notna() & ~result.isin(city_map.values())]
    if len(unmapped) > 0:
        print("\nTop 12 unmapped / unknown cities (add the frequent ones to map!):")
        print(unmapped.value_counts().head(12))
    else:
        print("\nAll non-null values were mapped to known cities — excellent!")

    return result

# ────────────────────────────────────────────────
# Apply to both columns
df['user_city']     = normalize_city_advanced('user_location')
df['merchant_city'] = normalize_city_advanced('merchant_location')

# Optional cleanup
# df = df.drop(columns=['user_location', 'merchant_location'])

import pandas as pd
import numpy as np

# ────────────────────────────────────────────────
# Expanded map based on YOUR actual top unmapped cities
city_map = {
    # Previous strong ones
    'mumbai': 'Mumbai', 'bombay': 'Mumbai', 'bom': 'Mumbai', 'mum': 'Mumbai',
    'bangalore': 'Bengaluru', 'bengaluru': 'Bengaluru', 'banglore': 'Bengaluru',
    'chennai': 'Chennai', 'madras': 'Chennai',
    'kolkata': 'Kolkata', 'calcutta': 'Kolkata',
    'delhi': 'Delhi', 'new delhi': 'Delhi', 'ncr': 'Delhi',

    # ── NEW: From your Top unmapped ───────────────────────────────
    # Jai → almost certainly Jaipur (very common abbreviation)
    'jai': 'Jaipur', 'jaipur': 'Jaipur', 'jpr': 'Jaipur',

    # Lko → Lucknow
    'lko': 'Lucknow', 'lucknow': 'Lucknow', 'lknw': 'Lucknow',

    # Pnq → Pune
    'pnq': 'Pune', 'pune': 'Pune', 'pnq ': 'Pune',

    # Ccu → Kolkata (CCU = Netaji Subhas Chandra Bose Intl Airport code)
    'ccu': 'Kolkata',

    # Del → Delhi (DEL = Indira Gandhi Intl Airport code)
    'del': 'Delhi',

    # Amd → Ahmedabad
    'amd': 'Ahmedabad', 'ahmedabad': 'Ahmedabad',

    # Maa → Chennai (MAA = Chennai International Airport code)
    'maa': 'Chennai',

    # International ones that appear (even if few)
    'dubai': 'Dubai',
    'new york': 'New York', 'ny': 'New York',
    'bangkok': 'Bangkok',
    'singapore': 'Singapore',

    # Optional extras you might see next (add if they appear in next run)
    # 'hyd': 'Hyderabad', 'blr': 'Bengaluru', 'pat': 'Patna', 'sur': 'Surat',
}

# ────────────────────────────────────────────────
def normalize_city_advanced(col_name):
    """
    Returns normalized city names + detailed success statistics
    """
    # Step 1: clean input
    s = df[col_name].astype(str).str.lower().str.strip()

    # Step 2: treat obvious missing/invalid as NaN
    missing_markers = ['', 'nan', 'na', 'n/a', 'null', '-', 'unknown', 'none', 'nil', 'missing']
    s = s.replace(missing_markers, np.nan)

    # Step 3: map known aliases
    mapped = s.map(city_map)

    # Step 4: fallback → title case only for plausible city-like strings
    fallback = s.str.title()
    # Protect very short junk (1-3 chars that aren't in map) → NaN
    fallback = np.where(
        (s.str.len() <= 3) & (~s.isin(city_map.keys())), np.nan, fallback
    )

    result = mapped.combine_first(pd.Series(fallback, index=s.index))

    # ── Statistics ────────────────────────────────────────
    total_rows = len(df)
    original_non_null = df[col_name].notna().sum()
    after_non_null   = result.notna().sum()
    mapped_to_known  = result.isin(city_map.values()).sum()

    print(f"\n=== LOCATION NORMALIZATION REPORT: {col_name} ===")
    print(f"Total rows                     : {total_rows:,}")
    print(f"Original non-null values       : {original_non_null:,} ({original_non_null/total_rows*100:.2f}%)")
    print(f"After normalization non-null   : {after_non_null:,} ({after_non_null/total_rows*100:.2f}%)")
    print(f"→ Mapped to known canonical    : {mapped_to_known:,} ({mapped_to_known/total_rows*100:.2f}%)")
    print(f"→ Title-cased (still unknown)  : {after_non_null - mapped_to_known:,} ({(after_non_null - mapped_to_known)/total_rows*100:.2f}%)")

    # Show remaining unmapped (should be much fewer now)
    unmapped = result[result.notna() & ~result.isin(city_map.values())]
    if len(unmapped) > 0:
        print("\nRemaining top unmapped / unknown cities:")
        print(unmapped.value_counts().head(12))
    else:
        print("\nAll non-null values mapped to known cities — perfect coverage!")

    return result

# ────────────────────────────────────────────────
# Apply to both columns
df['user_city']     = normalize_city_advanced('user_location')
df['merchant_city'] = normalize_city_advanced('merchant_location')

# Optional: drop originals if you no longer need them
# df = df.drop(columns=['user_location', 'merchant_location'])

# ────────────────────────────────────────────────
# FINAL expanded map — should get you to 94–97% mapped
city_map = {
    # Previous strong ones (keep them all)
    'mumbai': 'Mumbai', 'bombay': 'Mumbai', 'bom': 'Mumbai', 'mum': 'Mumbai',
    'bangalore': 'Bengaluru', 'bengaluru': 'Bengaluru', 'banglore': 'Bengaluru',
    'chennai': 'Chennai', 'madras': 'Chennai',
    'kolkata': 'Kolkata', 'calcutta': 'Kolkata',
    'delhi': 'Delhi', 'new delhi': 'Delhi', 'ncr': 'Delhi',
    'jai': 'Jaipur', 'jaipur': 'Jaipur',
    'lko': 'Lucknow', 'lucknow': 'Lucknow',
    'pnq': 'Pune', 'pune': 'Pune',
    'ccu': 'Kolkata',
    'del': 'Delhi',
    'amd': 'Ahmedabad', 'ahmedabad': 'Ahmedabad',
    'maa': 'Chennai',

    # ── NEW additions based on your latest unmapped ───────
    'hyderabad': 'Hyderabad', 'hyd': 'Hyderabad', 'hyderbad': 'Hyderabad',
    'hyder': 'Hyderabad', 'hyderab': 'Hyderabad',   # partial matches

    # International (small volume but clean up)
    'dubai': 'Dubai',
    'new york': 'New York',
    'bangkok': 'Bangkok',
    'singapore': 'Singapore',
}

# ────────────────────────────────────────────────
def normalize_city_final(col_name):
    s = df[col_name].astype(str).str.lower().str.strip()

    # Missing / junk markers
    missing_markers = ['', 'nan', 'na', 'n/a', 'null', '-', 'unknown', 'none', 'nil', 'missing']
    s = s.replace(missing_markers, np.nan)

    # Junk filter: patterns like J..., Luc#, Jai??, De... → set to NaN
    junk_mask = s.str.contains(r'[#\?\.]{2,}', na=False)
    s = s.where(~junk_mask, np.nan)

    # Map known aliases
    mapped = s.map(city_map)

    # Fallback: title case only for plausible strings
    fallback = s.str.title()
    # Protect very short / suspicious strings
    short_or_junk = (s.str.len() < 4) | s.str.contains(r'[#\?\.]', na=False)
    fallback = fallback.where(~short_or_junk, np.nan)

    result = mapped.combine_first(fallback)

    # ── Statistics ────────────────────────────────────────
    total = len(df)
    orig_nonnull = df[col_name].notna().sum()
    after_nonnull = result.notna().sum()
    mapped_known = result.isin(city_map.values()).sum()

    print(f"\n=== FINAL LOCATION NORMALIZATION REPORT: {col_name} ===")
    print(f"Total rows                     : {total:,}")
    print(f"Original non-null              : {orig_nonnull:,} ({orig_nonnull/total*100:.2f}%)")
    print(f"After normalization non-null   : {after_nonnull:,} ({after_nonnull/total*100:.2f}%)")
    print(f"→ Mapped to known canonical    : {mapped_known:,} ({mapped_known/total*100:.2f}%)")
    print(f"→ Title-cased (still unknown)  : {after_nonnull - mapped_known:,} ({(after_nonnull - mapped_known)/total*100:.2f}%)")

    unmapped = result[result.notna() & ~result.isin(city_map.values())]
    if len(unmapped) > 0:
        print("\nRemaining unmapped cities:")
        print(unmapped.value_counts().head(15))
    else:
        print("\nPerfect — all non-null values mapped!")

    return result

df

import pandas as pd
import numpy as np

def location_normalization_success_report():
    """
    Prints detailed success rate and quality metrics for user_city and merchant_city
    after normalization has been applied.
    """
    print("\n" + "="*70)
    print("     LOCATION NORMALIZATION SUCCESS & QUALITY REPORT")
    print("="*70 + "\n")

    total_rows = len(df)

    for col in ['user_city', 'merchant_city']:
        print(f"→ Column: {col}")
        print("-"*60)

        # Basic counts
        total_non_null_original = df['user_location' if 'user' in col else 'merchant_location'].notna().sum()
        valid_after = df[col].notna().sum()
        mapped_to_known = df[col].isin(city_map.values()).sum()
        still_unknown = valid_after - mapped_to_known
        became_nan = total_rows - valid_after

        # Percentages
        pct_valid_original = total_non_null_original / total_rows * 100
        pct_valid_after    = valid_after / total_rows * 100
        pct_mapped_known   = mapped_to_known / total_rows * 100
        pct_still_unknown  = still_unknown / total_rows * 100
        pct_nan            = became_nan / total_rows * 100

        print(f"Total rows                          : {total_rows:,}")
        print(f"Original non-null values            : {total_non_null_original:,} ({pct_valid_original:.2f}%)")
        print(f"After normalization - valid values  : {valid_after:,} ({pct_valid_after:.2f}%)")
        print(f"   └─ Mapped to known city          : {mapped_to_known:,} ({pct_mapped_known:.2f}%)")
        print(f"   └─ Still unknown (title-cased)   : {still_unknown:,} ({pct_still_unknown:.2f}%)")
        print(f"Became NaN (missing or junk)        : {became_nan:,} ({pct_nan:.2f}%)")

        # Show top remaining unknown values
        if still_unknown > 0:
            print("\nTop remaining unknown (title-cased) values:")
            unknown_values = df[col][~df[col].isin(city_map.values()) & df[col].notna()]
            if len(unknown_values) > 0:
                print(unknown_values.value_counts().head(15).to_string())
            else:
                print("   (none found)")
        else:
            print("\nAll valid values mapped to known cities — excellent!")

        print("\n")

# ────────────────────────────────────────────────
# Run the report
location_normalization_success_report()

df

import pandas as pd
import numpy as np
import re

def clean_and_flag_ip(df, ip_col='ip_address'):
    """
    Clean ip_address and create fraud-useful features.
    """
    s = df[ip_col].astype(str).str.strip()

    # 1. Missing patterns
    missing_patterns = [
        r'^\s*$',
        r'^(NA|N/A|null|None|-|unknown|missing|private|vpn)$',
        r'^[\-–—]$'
    ]
    is_missing = s.str.match('|'.join(missing_patterns), na=False) | s.isna()

    # 2. Looks like IPv4 pattern
    ipv4_pattern = r'^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$'
    looks_like_ipv4 = s.str.match(ipv4_pattern, na=False)

    # 3. Valid octets 0–255
    def valid_octets(ip_str):
        if not isinstance(ip_str, str) or pd.isna(ip_str):
            return False
        try:
            parts = [int(x) for x in ip_str.split('.') if x or x == '0']
            return len(parts) == 4 and all(0 <= p <= 255 for p in parts)
        except:
            return False

    is_valid_format = looks_like_ipv4 & s.apply(valid_octets)

    # 4. Special cases
    is_localhost = s.isin(['127.0.0.1', 'localhost', '::1'])
    is_zero_ip   = s == '0.0.0.0'
    is_private   = s.str.startswith(('10.', '192.168.', '172.16.', '172.17.', '172.18.', '172.19.',
                                     '172.20.', '172.21.', '172.22.', '172.23.', '172.24.', '172.25.',
                                     '172.26.', '172.27.', '172.28.', '172.29.', '172.30.', '172.31.'))

    # 5. Create features
    df['ip_clean'] = np.where(is_valid_format, s, np.nan)

    df['is_valid_ipv4'] = (
        is_valid_format &
        ~is_localhost &
        ~is_zero_ip
    ).astype(int)

    df['ip_anomaly'] = (
        is_missing |
        ~is_valid_format |
        is_localhost |
        is_zero_ip
    ).astype(int)

    # FIXED: np.select – all choices are strings + explicit default
    df['ip_present'] = np.select(
        condlist=[
            df['is_valid_ipv4'] == 1,
            is_missing,
            is_localhost | is_zero_ip,
        ],
        choicelist=[
            'valid',
            'missing',
            'localhost/zero',
        ],
        default='malformed'          # ← string, matches choicelist dtype
    )

    # 6. Summary
    print("IP Address Cleaning Summary:")
    print("────────────────────────────")
    print(f"Total rows:               {len(df):,}")
    print(f"Original missing/empty:   {is_missing.sum():,} ({is_missing.mean():.2%})")
    print(f"Valid IPv4 format:        {is_valid_format.sum():,} ({is_valid_format.mean():.2%})")
    print(f"Strict valid IPv4:        {df['is_valid_ipv4'].sum():,} ({df['is_valid_ipv4'].mean():.2%})")
    print(f"Anomaly flag (1=suspicious): {df['ip_anomaly'].sum():,} ({df['ip_anomaly'].mean():.2%})")
    print("\nip_present value counts:")
    print(df['ip_present'].value_counts(dropna=False))

    suspicious = df[df['ip_anomaly'] == 1][ip_col].value_counts().head(15)
    if not suspicious.empty:
        print("\nTop 15 suspicious IP values:")
        print(suspicious)

    return df


# ────────────────────────────────────────────────
# Run it
df = clean_and_flag_ip(df, ip_col='ip_address')

# Optional: quick inspection
print("\nSample suspicious rows:")
print(df[df['ip_anomaly'] == 1][['ip_address', 'ip_clean', 'is_valid_ipv4', 'ip_anomaly', 'ip_present']].head(10))

# A. Same IP used by many users
ip_user_count = df.groupby('ip_clean')['user_id'].nunique()
df['ip_multi_user'] = df['ip_clean'].map(ip_user_count).fillna(1)
df['ip_multi_user_flag'] = (df['ip_multi_user'] > 3).astype(int)

# B. IP is private network
df['ip_is_private'] = df['ip_clean'].str.startswith(
    ('10.', '192.168.', '172.16.', '172.17.', '172.18.', '172.19.',
     '172.20.', '172.21.', '172.22.', '172.23.', '172.24.', '172.25.',
     '172.26.', '172.27.', '172.28.', '172.29.', '172.30.', '172.31.'),
    na=False   # ← this prevents NaN → float error
).astype(int)

# C. Masked IP (contains 'x')
df['ip_masked'] = df['ip_address'].str.contains('x', case=False, na=False).astype(int)

# D. Invalid octet (contains invalid numbers)
df['ip_invalid_octet'] = (
    df['ip_anomaly'] &
    df['ip_address'].str.contains(r'999|256|>|>255', na=False)
).astype(int)

# Quick check
print("New IP feature means:")
print(df[['ip_multi_user_flag', 'ip_is_private', 'ip_masked', 'ip_invalid_octet']].mean())

print("\nTop IPs shared by multiple users:")
print(ip_user_count[ip_user_count > 2].sort_values(ascending=False).head(10))

import re

# ─── Step 1: Create cleaned IP column ───
def clean_ip(ip):
    if pd.isna(ip) or str(ip).strip() == '':
        return None
    ip_str = str(ip).strip().lower()
    # Remove common junk
    ip_str = re.sub(r'\s+', '', ip_str)
    # Basic IPv4 pattern match
    match = re.match(r'^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$', ip_str)
    if match:
        octets = [int(o) for o in match.groups()]
        if all(0 <= o <= 255 for o in octets):
            return '.'.join(map(str, octets))
    return None  # invalid → None

df['ip_clean'] = df['ip_address'].apply(clean_ip)

# ─── Step 2: Validation flags (already have some, add more) ───
df['ip_valid_format'] = df['ip_clean'].notna().astype(int)
df['ip_is_private'] = df['ip_clean'].str.startswith(
    ('10.', '192.168.', '172.16.', '172.17.', '172.18.', '172.19.',
     '172.20.', '172.21.', '172.22.', '172.23.', '172.24.', '172.25.',
     '172.26.', '172.27.', '172.28.', '172.29.', '172.30.', '172.31.'),
    na=False
).astype(int)

df['ip_masked'] = df['ip_address'].str.contains('x', case=False, na=False).astype(int)

# ─── Step 3: Success & quality metrics ───
print("\nIP VALIDATION REPORT")
valid_ips = df['ip_valid_format'].sum()
total_rows = len(df)
print(f"Valid IPv4 format after cleaning: {valid_ips:,} / {total_rows:,}  ({valid_ips/total_rows*100:.2f}%)")

invalid_ips = total_rows - valid_ips
print(f"Invalid / unparseable IPs: {invalid_ips:,}  ({invalid_ips/total_rows*100:.2f}%)")

private_ips = df['ip_is_private'].sum()
print(f"Private network IPs (RFC 1918): {private_ips:,}  ({private_ips/total_rows*100:.2f}%)")

masked_ips = df['ip_masked'].sum()
print(f"Masked IPs (contain 'x'): {masked_ips:,}  ({masked_ips/total_rows*100:.2f}%)")

# Sample of cleaned vs original
print("\nSample of IP cleaning results:")
print(df[['ip_address', 'ip_clean', 'ip_valid_format', 'ip_is_private', 'ip_masked']].head(15))

# Success rate
ip_success_rate = (valid_ips / total_rows) * 100
print(f"\nIP cleaning & validation success rate: {ip_success_rate:.2f}%")

# ─── Step 1: Quantify missingness per column ───
print("\nMissing value report BEFORE handling:")
missing = df.isna().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'missing_count': missing, 'missing_pct': missing_pct})
print(missing_df[missing_df['missing_count'] > 0].sort_values('missing_pct', ascending=False))

# ─── Step 2: Create missing flags for important columns ───
important_cols = ['amount', 'ts', 'user_city', 'merchant_city', 'device_id', 'ip_address', 'account_balance']
for col in important_cols:
    if col in df.columns:
        df[f'is_missing_{col}'] = df[col].isna().astype(int)

# ─── Step 3: Imputation strategy ───
# Amount: median per user (behavioral)
if 'amount' in df.columns:
    df['amount'] = df.groupby('user_id')['amount'].transform(lambda x: x.fillna(x.median()))
    # If user has no non-null → global median
    df['amount'] = df['amount'].fillna(df['amount'].median())

# ts: drop rows where timestamp could not be parsed (critical for time features)
ts_missing_before = df['ts'].isna().sum()
df = df[df['ts'].notna()]
print(f"Dropped {ts_missing_before:,} rows due to unparseable timestamps")

# Cities: fill with 'Unknown'
for col in ['user_city', 'merchant_city']:
    df[col] = df[col].fillna('Unknown')

# device_id, ip_address: fill with 'missing_device', 'missing_ip'
df['device_id'] = df['device_id'].fillna('missing_device')
df['ip_address'] = df['ip_address'].fillna('missing_ip')

# account_balance: median per user or global
if 'account_balance' in df.columns:
    df['account_balance'] = df.groupby('user_id')['account_balance'].transform(lambda x: x.fillna(x.median()))
    df['account_balance'] = df['account_balance'].fillna(df['account_balance'].median())

# ─── Step 4: Final missing check & success rate ───
print("\nMissing value report AFTER handling:")
missing_after = df.isna().sum()
print(missing_after[missing_after > 0])

remaining_missing_pct = (df.isna().sum().sum() / (len(df) * len(df.columns))) * 100
print(f"Overall remaining missing values: {remaining_missing_pct:.3f}% of all cells")

success_rate_null = 100 - remaining_missing_pct
print(f"Null handling success rate (non-missing cells): {success_rate_null:.2f}%")

# ─── Step 1: Exact row duplicates ───
exact_dup_count_before = df.duplicated().sum()
print(f"Exact duplicate rows before removal: {exact_dup_count_before:,}")

df = df.drop_duplicates(keep='first')
exact_dup_count_after = df.duplicated().sum()

print(f"Exact duplicates removed: {exact_dup_count_before:,}")
print(f"Exact duplicate rows remaining: {exact_dup_count_after:,}")
print(f"Rows after exact dedup: {len(df):,}")

# ─── Step 2: Same transaction_id but different content ───
txid_dup = df['transaction_id'].value_counts()
txid_multi = txid_dup[txid_dup > 1]

print(f"\nTransaction IDs appearing more than once: {len(txid_multi):,}")
print(f"Total rows belonging to repeated transaction_ids: {txid_multi.sum():,}")

if len(txid_multi) > 0:
    print("\nSample conflicting transaction_ids:")
    print(txid_multi.head(8))

# extra rows that should be removed
extra_duplicate_rows = txid_multi.sum() - len(txid_multi)
print(f"Extra duplicate rows to resolve: {extra_duplicate_rows:,}")

# Better conflict strategy: keep most complete row, then latest timestamp
df['non_null_count'] = df.notna().sum(axis=1)
df = df.sort_values(['transaction_id', 'non_null_count', 'ts'])
df = df.groupby('transaction_id').tail(1).drop(columns='non_null_count').reset_index(drop=True)

print(f"\nRows after transaction_id deduplication: {len(df):,}")

remaining_duplicate_txids = df['transaction_id'].duplicated().sum()
print(f"Remaining duplicate transaction_ids: {remaining_duplicate_txids:,}")

if extra_duplicate_rows > 0:
    duplicate_resolution_rate = ((extra_duplicate_rows - remaining_duplicate_txids) / extra_duplicate_rows) * 100
else:
    duplicate_resolution_rate = 100.0

print(f"Duplicate resolution rate: {duplicate_resolution_rate:.2f}%")

"""TRAINING"""

user_stats = df.groupby('user_id')['transaction_amount'].agg(['mean','std','count']).reset_index()
user_stats.columns = ['user_id','user_avg_amount','user_std_amount','user_txn_count']

# Define columns to potentially drop before merge to prevent conflicts
cols_to_drop = [
    'user_avg_amount', 'user_std_amount', 'user_txn_count',
    'amount_vs_user_avg', 'amount_diff', 'amount_zscore'
]

# Drop existing columns if they are present in df
for col in cols_to_drop:
    if col in df.columns:
        df = df.drop(columns=[col])

# Merge user statistics
df = df.merge(user_stats, on='user_id', how='left')

# Amount deviation features
df['amount_vs_user_avg'] = df['transaction_amount'] / (df['user_avg_amount'] + 1)
df['amount_diff'] = df['transaction_amount'] - df['user_avg_amount']
df['amount_zscore'] = df['amount_diff'] / (df['user_std_amount'] + 1)

df['seconds_since_prev'] = df.groupby('user_id')['ts'].diff().dt.total_seconds().fillna(0)
df['txn_count_last_5min'] = (
    df.groupby('user_id')['seconds_since_prev']
      .transform(lambda x: (x < 300).cumsum())
)

df['hour'] = df['ts'].dt.hour
df['day_of_week'] = df['ts'].dt.dayofweek

df['is_night'] = ((df['hour'] >= 0) & (df['hour'] <= 5)).astype(int)
df['is_weekend'] = (df['day_of_week'] >= 5).astype(int)

# Device used by multiple users
device_user_count = df.groupby('device_id')['user_id'].nunique()
df['device_user_count'] = df['device_id'].map(device_user_count)

# New device for user
df['is_new_device_for_user'] = (
    df.groupby('user_id')['device_id']
      .transform(lambda x: ~x.duplicated())
).astype(int)

# Number of devices used by user
user_device_count = df.groupby('user_id')['device_id'].nunique()
df['user_device_count'] = df['user_id'].map(user_device_count)

# New city for user
df['is_new_city_for_user'] = (
    df.groupby('user_id')['user_city']
      .transform(lambda x: ~x.duplicated())
).astype(int)

# Location switch detection
df['prev_city'] = df.groupby('user_id')['user_city'].shift(1)

df['location_switch_flag'] = (
    (df['user_city'] != df['prev_city']) &
    df['prev_city'].notna()
).astype(int)

# Number of cities per user
user_city_count = df.groupby('user_id')['user_city'].nunique()
df['user_city_count'] = df['user_id'].map(user_city_count)

# Amount + velocity interaction
df['amount_velocity_interaction'] = df['amount_vs_user_avg'] * df['txn_count_last_5min']

# New device + new location (strong fraud signal)
df['device_location_combo'] = (
    df['is_new_device_for_user'] &
    df['is_new_city_for_user']
).astype(int)

# Night + high amount
df['night_amount_flag'] = (
    (df['is_night'] == 1) &
    (df['amount_vs_user_avg'] > 3)
).astype(int)

df['amount_to_balance_ratio'] = df['transaction_amount'] / (df['account_balance'] + 1)

df['amount_gt_balance'] = (df['transaction_amount'] > df['account_balance']).astype(int)

df

df[['amount_vs_user_avg',
    'txn_count_last_5min',
    'is_new_device_for_user',
    'is_new_city_for_user',
    'device_user_count']].describe()

df['amount_vs_user_avg'] = df['amount_vs_user_avg'].fillna(1)
df['txn_count_last_5min'] = df['txn_count_last_5min'].fillna(0)
df['seconds_since_prev'] = df['seconds_since_prev'].fillna(999999)

df['high_amount_flag'] = (df['amount_vs_user_avg'] > 3).astype(int)

df['velocity_flag'] = (df['txn_count_last_5min'] >= 2).astype(int)

df['multi_signal_flag'] = (
    df['high_amount_flag'] +
    df['velocity_flag'] +
    df['is_new_device_for_user'] +
    df['is_new_city_for_user']
)

"""STEP2: Training"""

# Core signals
df['high_amount_flag'] = (df['amount_vs_user_avg'] > 3).astype(int)
df['extreme_amount_flag'] = (df['amount_vs_user_avg'] > 6).astype(int)

df['velocity_flag'] = (df['txn_count_last_5min'] >= 2).astype(int)
df['fast_txn_flag'] = (df['seconds_since_prev'] < 60).astype(int)

# Combination already built
# df['multi_signal_flag'] exists (sum of signals)

# IP / device already built
# ip_multi_user_flag, ip_anomaly, device_user_count, is_new_device_for_user, is_new_city_for_user

# Score (weighted)
df['fraud_score'] = (
    3*df['extreme_amount_flag'] +
    2*df['high_amount_flag'] +
    2*df['velocity_flag'] +
    1*df['fast_txn_flag'] +
    2*df['is_new_device_for_user'] +
    2*df['is_new_city_for_user'] +
    2*df['device_location_combo'] +      # very strong signal
    2*df['ip_multi_user_flag'] +
    1*df['ip_anomaly'] +
    1*(df['device_user_count'] > 5).astype(int) +
    1*(df['amount_to_balance_ratio'] > 0.7).astype(int)
)

# Inspect distribution
df['fraud_score'].describe()
df['fraud_score'].value_counts().sort_index()

# Start with this threshold
THRESHOLD = 5

df['fraud_label'] = (df['fraud_score'] >= THRESHOLD).astype(int)

# Check balance
fraud_rate = df['fraud_label'].mean()
print("Fraud rate:", fraud_rate)

df.groupby('fraud_label')[[
    'amount_vs_user_avg',
    'txn_count_last_5min',
    'is_new_device_for_user',
    'is_new_city_for_user'
]].mean()

df['very_high_risk'] = (df['fraud_score'] >= 7).astype(int)

df['strong_combo_flag'] = (
    (df['is_new_device_for_user'] == 1) &
    (df['is_new_city_for_user'] == 1)
).astype(int)

df['fraud_score'] += 3 * df['strong_combo_flag']

THRESHOLD = 6   # slightly stricter now

df['fraud_label'] = (df['fraud_score'] >= THRESHOLD).astype(int)

print("New fraud rate:", df['fraud_label'].mean())

"""STEP 3: TRAINING"""

from sklearn.ensemble import IsolationForest

iso_features = [
    'transaction_amount',
    'amount_vs_user_avg',
    'txn_count_last_5min',
    'seconds_since_prev'
]

X_iso = df[iso_features].fillna(0)

iso = IsolationForest(
    n_estimators=200,
    contamination=0.05,
    random_state=42
)

iso.fit(X_iso)

# -1 = anomaly → convert to 1
df['anomaly_score'] = (iso.predict(X_iso) == -1).astype(int)

FEATURES = [
    'amount_vs_user_avg',
    'amount_zscore',
    'txn_count_last_5min',
    'seconds_since_prev',
    'is_new_device_for_user',
    'is_new_city_for_user',
    'device_user_count',
    'user_device_count',
    'location_switch_flag',
    'user_city_count',
    'ip_multi_user_flag',
    'ip_anomaly',
    'ip_is_private',
    'hour',
    'is_night',
    'amount_to_balance_ratio',
    'device_location_combo',
    'amount_velocity_interaction',
    'strong_combo_flag',
    'anomaly_score',
    'rolling_avg_3',
    'spike_flag'
]

X = df[FEATURES].fillna(0)
y = df['fraud_label']

from lightgbm import LGBMClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=31,
    class_weight='balanced'   # important for fraud
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

df['fraud_prob'] = model.predict_proba(X)[:, 1]

df['fraud_prob'].describe()

model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=15,
    max_depth=5,
    min_child_samples=30,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.5,
    reg_lambda=0.5,
    class_weight='balanced',
    random_state=42
)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from lightgbm import LGBMClassifier

model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=15,
    max_depth=5,
    min_child_samples=30,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.5,
    reg_lambda=0.5,
    class_weight='balanced',
    random_state=42
)

model.fit(X_train, y_train)

df['fraud_prob'] = model.predict_proba(X)[:,1]

df['fraud_prob'].describe()

"""STEP4:TRAINING"""

df['fraud_stage1'] = df['fraud_prob'] > 0.3

df['final_fraud'] = df['fraud_stage1'] & (
    (df['fraud_score'] >= 6) |
    (df['strong_combo_flag'] == 1) |
    (df['anomaly_score'] == 1)
)

def fraud_type(row):
    if row['strong_combo_flag'] == 1:
        return "Device + Location Fraud"
    elif row['amount_vs_user_avg'] > 5:
        return "High Amount Fraud"
    elif row['txn_count_last_5min'] >= 3:
        return "Velocity Fraud"
    elif row['is_new_device_for_user']:
        return "Device Fraud"
    elif row['is_new_city_for_user']:
        return "Location Fraud"
    else:
        return "Mixed Fraud"

df['fraud_type'] = df.apply(
    lambda x: fraud_type(x) if x['final_fraud'] == 1 else "Not Fraud",
    axis=1
)

from sklearn.metrics import classification_report

print(classification_report(y, df['final_fraud']))

"""STEP5: TRAINING"""

final_df = df[[
    'user_id',
    'transaction_amount',
    'ts',
    'device_id',
    'user_city',
    'fraud_prob',
    'final_fraud',
    'fraud_type'
]].copy()

final_df['fraud_label'] = final_df['final_fraud'].map({
    0: "Not Fraud",
    1: "Fraud"
})

total_txn = len(final_df)
fraud_count = final_df['final_fraud'].sum()
fraud_rate = fraud_count / total_txn

print("Total Transactions:", total_txn)
print("Fraud Count:", fraud_count)
print("Fraud Rate:", fraud_rate)

fraud_type_counts = final_df['fraud_type'].value_counts()
print(fraud_type_counts)

top_fraud = final_df.sort_values('fraud_prob', ascending=False).head(10)
print(top_fraud)

fraud_city = final_df[final_df['final_fraud'] == 1]['user_city'].value_counts()
print(fraud_city)

final_df['date'] = final_df['ts'].dt.date

fraud_time = final_df.groupby('date')['final_fraud'].sum()
print(fraud_time)

final_df.to_csv("fraud_detection_output.csv", index=False)

"""STEP6: TRAINING"""

from fastapi import FastAPI
import pandas as pd

app = FastAPI()

@app.post("/predict")
def predict(file):
    df = pd.read_csv(file.file)

    # pipeline
    # model

    return {"fraud_count": int(df['final_fraud'].sum())}

df['fraud_stage1'] = df['fraud_prob'] > THRESHOLD

df['final_fraud'] = df['fraud_stage1'] & (
    (df['fraud_score'] >= 4) |
    (df['txn_count_last_5min'] >= 4) |
    (df['anomaly_score'] == 1)
)

"""STEP7:TRAINING"""

def fraud_type(row):
    if row['amount_vs_user_avg'] > 5:
        return "High Amount Fraud"

    elif row['txn_count_last_5min'] >= 3:
        return "Velocity Fraud"

    elif row['is_new_device_for_user']:
        return "Device Fraud"

    elif row['is_new_city_for_user']:
        return "Location Fraud"

    elif row['ip_multi_user_flag']:
        return "Shared Device/IP Fraud"

    else:
        return "Mixed Fraud"

df['fraud_type'] = df.apply(fraud_type, axis=1)

total_txn = len(df)
fraud_count = df['final_fraud'].sum()
fraud_rate = fraud_count / total_txn

print("Total Transactions:", total_txn)
print("Fraud Detected:", fraud_count)
print("Fraud Rate:", fraud_rate)

total_txn = len(df)
fraud_count = df['final_fraud'].sum()
fraud_rate = fraud_count / total_txn

print("Total Transactions:", total_txn)
print("Fraud Detected:", fraud_count)
print("Fraud Rate:", fraud_rate)

df['fraud_type'].value_counts()

df.sort_values('fraud_prob', ascending=False).head(10)

df.to_csv("fraud_detection_output.csv", index=False)

predicted_fraud = df['final_fraud'].sum()
total_txn = len(df)

print("Predicted Fraud Count:", predicted_fraud)
print("Total Transactions:", total_txn)
print("Fraud Rate:", predicted_fraud / total_txn)

predicted_fraud = df['final_fraud'].sum()
total_txn = len(df)

print("Predicted Fraud Count:", predicted_fraud)
print("Total Transactions:", total_txn)
print("Fraud Rate:", predicted_fraud / total_txn)

df['fraud_prob'].describe()

df['fraud_stage1'] = df['fraud_prob'] > 0.3
print("Stage 1 frauds:", df['fraud_stage1'].sum())

df['final_fraud'] = df['fraud_stage1'] & (
    (df['fraud_score'] >= 7) |
    (
        (df['strong_combo_flag'] == 1) &
        (df['fraud_score'] >= 6)
    ) |
    (
        (df['anomaly_score'] == 1) &
        (df['fraud_score'] >= 6)
    )
)

print("Stage 2 frauds:", df['final_fraud'].sum())

print("Stage 1:", df['fraud_stage1'].sum())
print("Final Fraud:", df['final_fraud'].sum())

import joblib

joblib.dump(model, "model.pkl")

final_df

from sklearn.model_selection import train_test_split

X = df[FEATURES].fillna(0)
y = df['fraud_label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

from sklearn.metrics import roc_auc_score

y_prob = model.predict_proba(X_test)[:,1]

print("ROC-AUC:", roc_auc_score(y_test, y_prob))

import joblib

joblib.dump(model, "model.pkl")

from google.colab import files

files.download("model.pkl")

"""# Task
Update the fraud detection model's features by adding 'iso_score', 'rolling_avg_3', 'spike_flag', and 'ip_multi_user_flag' to the existing `FEATURES` list. Then, implement an ensemble model by training a `RandomForestClassifier` alongside the current `LightGBMClassifier` using the updated feature set. Generate probability predictions from both models and combine them into a new 'ensemble_fraud_prob' column using a weighted average of 0.6 for LightGBM and 0.4 for Random Forest. Set a prediction threshold of 0.4 for 'ensemble_fraud_prob' to derive the 'final_fraud' predictions, and evaluate the ensemble model's performance using accuracy, precision, recall, and F1 score. Finally, provide a summary of the overall improvements achieved by this hybrid fraud detection system.

## Update Model Features

### Subtask:
Modify the 'FEATURES' list in the notebook to incorporate the newly generated features: 'iso_score' (from Isolation Forest), 'rolling_avg_3', 'spike_flag' (from sequence features), and 'ip_risk_flag' (from IP risk analysis). This ensures these new signals are used in the model training process.

# Task
Update the fraud detection model's features by including 'iso_score', 'rolling_avg_3', 'spike_flag', and 'ip_risk_flag' (using 'ip_multi_user_flag' if 'ip_risk_flag' is not present) in the `FEATURES` list. Then, create an ensemble model by training both a `LightGBMClassifier` and a `RandomForestClassifier` with the refined feature set. Combine their predictions with weights (0.6 for LightGBM, 0.4 for RandomForest) into an 'ensemble_fraud_prob' column. Finally, generate 'final_fraud' predictions using a 0.4 threshold on 'ensemble_fraud_prob' and evaluate the ensemble model's performance by calculating accuracy, precision, recall, and F1 score.

## Ensure Feature Creation

### Subtask:
Ensure all necessary features, including 'iso_score', 'rolling_avg_3', 'spike_flag', and 'ip_multi_user_flag', as well as 'amount_vs_user_avg', 'amount_zscore', 'seconds_since_prev', 'txn_count_last_5min', and 'amount_to_balance_ratio', are correctly computed and added to the DataFrame `df`.

# Task
```python
df['rolling_avg_3'] = df.groupby('user_id')['transaction_amount'].transform(lambda x: x.rolling(3, min_periods=1).mean())
df['spike_flag'] = (df['transaction_amount'] > 2 * df['rolling_avg_3']).astype(int)
```

## Ensure Rolling Avg and Spike Flag Features

### Subtask:
Execute the cell that creates 'rolling_avg_3' and 'spike_flag' based on user transaction history.
"""